### ISSUE TITLE
updateRecall doesn't support floating point scores

### ISSUE THREAD

**Issue by BieniekAlexander** [fasiha/ebisu.js#18]
Version: `"ebisu-js": "^2.0.0"`

The [python implementation of Ebisu](https://github.com/fasiha/ebisu#quickstart) currently supports floating point values for `updateRecall`:
```
>>> import ebisu
>>> model = (2,2,24)
>>> recall_score = .7
>>> dt = 24
>>> ebisu.updateRecall(model, recall_score, 1, dt)
(1.9157925909193039, 1.9157925909193065, 27.597608238946)
```

I find this useful in my application because I'm ripping out my Anki SM2 implementation in favor of this, and, I'd like to continue providing multiple "recall score" options to the user. Currently, when I provide a recall_score in the range [0,1], I get some sort of error:
```
> const ebisu = require('ebisu-js')
> ebisu.updateRecall([2,2,24], .7, 1, 24)
Uncaught RangeError: Invalid array length
    at Object.updateRecall (/home/alex/projects/ltt/frontend/shared/node_modules/ebisu-js/index.js:102:31)
```

**Comment by fasiha** [comment]
Ah yes, this JavaScript port is lagging Ebisu 😓, the Python implementation is 2.1 which is where soft-binary quizzes were added (floating point “successes”), and this repo is still 2.0, see the changelog https://github.com/fasiha/ebisu/blob/gh-pages/CHANGELOG.md

#12 is tracking this feature. Let me see if I can get this JS port to 2.1, I don’t think it will be hard.

**Comment by BieniekAlexander** [comment]
@fasiha Do you have a timeline? I'd be happy to contribute. :)

**Comment by fasiha** [comment]
Thanks @BieniekAlexander, yeah! I'm just in the process of translating https://github.com/fasiha/ebisu/blob/gh-pages/ebisu/ebisu.py to TypeScript, using ChatGPT for the bulk of the work 😆, I'm hoping to finish it this weekend but will be more than happy to receive a PR if you get there first!

**Comment by fasiha** [comment]
@BieniekAlexander I'd love any feedback in my PR upgrading this package to 2.1, in #19!
