### ISSUE TITLE
Return for `modelToPercentileDecay` not multiplied to `t0`

### ISSUE THREAD

**Issue by jasonsparc** [fasiha/ebisu.js#3]
https://github.com/fasiha/ebisu.js/blob/b280e18955ef958ad4ceb4890226c6eee0b59460/dist/ebisu.js#L117

For `modelToPercentileDecay`, it seems that at this line, the return value should have been multiplied by `t0`, just like in the python implementation.

**Comment by fasiha** [comment]
Thank you so much for catching this! I am dreadfully ashamed that this bug made it through reviews and tests 😭.
