### ISSUE TITLE
`error` should have been `new Error` instead

### ISSUE THREAD

**Issue by jasonsparc** [fasiha/ebisu.js#4]
Hi! I would like to report a non-critical issue, about `error` being not defined in:

https://github.com/fasiha/ebisu.js/blob/18afe562534e407ab8ea1d37c7f2e6c6828d5c0a/dist/ebisu.js#L116

Which apparently should have been `new Error` instead, to match up with the others.

**Comment by fasiha** [comment]
2000% right, how awful, thank you so much for catching this!!!

I don't know what inputs could cause the function to reach that point of the code 😟 Robert Kern who designed that algorithm made it bulletproof. A good problem to have 😊!

**Comment by jasonsparc** [comment]
Thank you so much for fixing this! :)

I did reach it on my code by using a much lower tolerance value of `1e-18`, while playing around and testing with some values. Though, I'll likely won't use a tolerance value of that low in my production code.

**Comment by fasiha** [comment]
Ahhha, yes, that'll do it! I added a test to ensure that unattainable tolerances will cause that failure.

Right, machine precision for doubles is roughly 2e-16, i.e., `(1+n) === 1` will be true if `n<2e-16` (roughly), so you certainly never want to go smaller than that.

It's also sometimes a bit unclear what the relationship between tolerance and runtime is—sometimes tightening the tolerance by 10x only means one or two more iterations of the search, sometimes it means 1000x more iterations. In this case, the error function is well-behaved (that is, not flat) for most of the domain, so tightening the tolerance hopefully won't aggravate runtime—though maybe note the error function will get quite flat as `percentile` goes to 0, i.e., for very low recall probabilities, you're at the tail of the recall's exponential decay, and the bracketed search may have to work hard to meet the tolerance.

Let me know if you feel I should make the default tolerance for non-coarse mode something other than 1e-4, the current default.
